language: node_js
node_js:
- stable

branches:
  only:
  - master

cache:
  directories:
    - "node_modules"

before_install:
  - git config credential.helper "store --file=.git/credentials"; echo "https://${GITHUB_TOKEN}@github.com:dugin/bookstore.git" > .git/credentials 2>/dev/null
  - git config --global user.email "rodrigodugin@gmail.com"
  - git config --global user.name "Rodrigo Dugin"

before_script:
  - npm install -g create-react-app

script:
  - npm install
  - npm run test:CI

after_success:
  - npm run build

deploy:
  provider: pages
  keep-history: true
  verbose: true
  skip-cleanup: true
  github-token:
     secure: GITHUB_TOKEN
  local_dir: build
  on:
   branch: master