language: node_js
node_js:
- stable

branches:
  only:
  - master

cache:
  directories:
    - "node_modules"

before_install:
  - git config credential.helper "store --file=.git/credentials"; echo "git@github.com:dugin/bookstore.git" > .git/credentials 2>/dev/null
  - git config --global user.email "rodrigodugin@gmail.com"
  - git config --global user.name "Rodrigo Dugin"

before_script:
  - npm install -g create-react-app

script:
  - npm install
  - npm run test:CI

after_success:
  - npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: GITHUB_TOKEN
 local_dir: build
 on:
   branch: master