language: node_js
node_js:
- stable

branches:
  only:
  - gh-pages
  - /.*/

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g create-react-app

script:
  - npm install
  - npm run test:CI

after_success:
  - npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: build
 on:
   branch: master